import type { Knex } from 'knex'
import { v4 as uuid } from 'uuid'

export async function seed(knex: Knex): Promise<void> {
  // 清理（保护外键依赖顺序：先删子表再删父表）
  await knex('project_documents').del()
  await knex('access_conditions').del()
  await knex('feasibility_assessments').del()
  await knex('projects').del()

  const types = await knex('project_types').select('id', 'code', 'name')
  const typeMap: Record<string, string> = {}
  for (const t of types) {
    typeMap[(t as any).code] = (t as any).id
  }

  const adminUser = await knex('users').where('username', 'admin').select('id').first()
  const adminId = adminUser?.id

  const now = new Date().toISOString()

  // ==================== 项目数据 ====================
  const projects = [
    {
      id: uuid(),
      project_code: 'PV-GC-2024-001',
      project_name: '华洋山地光伏电站（规划）',
      project_type: typeMap['PV_GRID_CONNECTION'],
      pv_type: '集中式',
      capacity_kw: 155000,
      budget: '62000',
      status: 'operation',
      start_date: '2024-01-01',
      expected_completion_date: '2024-08-01',
      actual_completion_date: '2024-08-30',
      created_by: adminId,
      created_at: now,
      updated_at: now,
      custom_fields: JSON.stringify({
        capacity_mwp: '155',
        land_type: '未利用地',
        grid_voltage: '110kV',
        target_substation: '建德变110kV',
        access_approval_status: '已取得',
        filing_status: '已备案',
        planned_grid_date: '2024-08-30',
        construction_progress: '已完工',
        operation_status: '正常运行',
        annual_irradiance: '1350',
        sunshine_hours: '1450',
        solar_grade: 'B',
        unit_cost: '4.0',
        payback_years: '8.5',
        irr_pct: '10.2',
        env_sensitivity: '一般',
        geohazard_risk: '低',
        short_circuit_capacity_mva: '350',
        transmission_distance_km: '3.2',
        corridor_available: '可用',
      }),
    },
    {
      id: uuid(),
      project_code: 'PV-GC-2024-002',
      project_name: '临安青山集中式光伏电站（规划）',
      project_type: typeMap['PV_GRID_CONNECTION'],
      pv_type: '集中式',
      capacity_kw: 60000,
      budget: '24000',
      status: 'construction',
      start_date: '2024-03-01',
      expected_completion_date: '2025-06-01',
      actual_completion_date: null,
      created_by: adminId,
      created_at: now,
      updated_at: now,
      custom_fields: JSON.stringify({
        capacity_mwp: '60',
        land_type: '农用地',
        grid_voltage: '110kV',
        target_substation: '临安变110kV',
        access_approval_status: '已取得',
        filing_status: '已备案',
        planned_grid_date: '2025-06-01',
        construction_progress: '设备安装',
        operation_status: '在建',
        annual_irradiance: '1400',
        sunshine_hours: '1520',
        solar_grade: 'A',
        unit_cost: '4.0',
        payback_years: '8.0',
        irr_pct: '11.5',
        env_sensitivity: '一般',
        geohazard_risk: '低',
        short_circuit_capacity_mva: '280',
        transmission_distance_km: '1.8',
        corridor_available: '可用',
      }),
    },
    {
      id: uuid(),
      project_code: 'PV-GC-2024-003',
      project_name: '萧山南阳集中式光伏电站（规划）',
      project_type: typeMap['PV_GRID_CONNECTION'],
      pv_type: '集中式',
      capacity_kw: 50000,
      budget: '20000',
      status: 'approved',
      start_date: '2024-04-01',
      expected_completion_date: '2025-09-01',
      actual_completion_date: null,
      created_by: adminId,
      created_at: now,
      updated_at: now,
      custom_fields: JSON.stringify({
        capacity_mwp: '50',
        land_type: '建设用地',
        grid_voltage: '10kV',
        target_substation: '萧山10kV',
        access_approval_status: '已取得',
        filing_status: '已备案',
        planned_grid_date: '2025-09-01',
        construction_progress: '未开工',
        operation_status: '在建',
        annual_irradiance: '1420',
        sunshine_hours: '1550',
        solar_grade: 'A',
        unit_cost: '4.0',
        payback_years: '7.8',
        irr_pct: '12.0',
        env_sensitivity: '不敏感',
        geohazard_risk: '低',
        short_circuit_capacity_mva: '120',
        transmission_distance_km: '0.5',
        corridor_available: '可用',
      }),
    },
    {
      id: uuid(),
      project_code: 'PV-GC-2025-001',
      project_name: '钱塘区舒能渔光互补（规划）',
      project_type: typeMap['PV_GRID_CONNECTION'],
      pv_type: '集中式',
      capacity_kw: 400000,
      budget: '160000',
      status: 'feasibility',
      start_date: '2025-01-01',
      expected_completion_date: '2026-06-01',
      actual_completion_date: null,
      created_by: adminId,
      created_at: now,
      updated_at: now,
      custom_fields: JSON.stringify({
        capacity_mwp: '400',
        land_type: '水域',
        grid_voltage: '220kV',
        target_substation: '钱塘变220kV',
        access_approval_status: '办理中',
        filing_status: '备案中',
        planned_grid_date: '2026-06-01',
        construction_progress: '未开工',
        operation_status: '在建',
        annual_irradiance: '1380',
        sunshine_hours: '1480',
        solar_grade: 'A',
        unit_cost: '3.8',
        payback_years: '7.2',
        irr_pct: '13.5',
        env_sensitivity: '一般',
        geohazard_risk: '低',
        short_circuit_capacity_mva: '600',
        transmission_distance_km: '2.5',
        corridor_available: '可用',
      }),
    },
    {
      id: uuid(),
      project_code: 'PV-ST-2024-001',
      project_name: '余杭光储联合示范项目',
      project_type: typeMap['PV_STORAGE'],
      pv_type: '集中式',
      capacity_kw: 30000,
      budget: '18000',
      status: 'feasibility',
      start_date: '2024-06-01',
      expected_completion_date: '2025-12-01',
      actual_completion_date: null,
      created_by: adminId,
      created_at: now,
      updated_at: now,
      custom_fields: JSON.stringify({
        capacity_mwp: '30',
        storage_capacity_mwh: '10',
        land_type: '未利用地',
        grid_voltage: '35kV',
        target_substation: '余杭变35kV',
        access_approval_status: '办理中',
        filing_status: '已备案',
        planned_grid_date: '2025-12-01',
        construction_progress: '未开工',
        operation_status: '在建',
        annual_irradiance: '1380',
        sunshine_hours: '1500',
        solar_grade: 'A',
        unit_cost: '4.5',
        payback_years: '9.0',
        irr_pct: '9.8',
        env_sensitivity: '不敏感',
        geohazard_risk: '低',
      }),
    },
    {
      id: uuid(),
      project_code: 'PV-DT-2024-001',
      project_name: '临安太湖源分布式光伏项目',
      project_type: typeMap['PV_DISTRIBUTED'],
      pv_type: '分布式',
      capacity_kw: 3000,
      budget: '1200',
      status: 'initiated',
      start_date: '2024-07-01',
      expected_completion_date: '2025-03-01',
      actual_completion_date: null,
      created_by: adminId,
      created_at: now,
      updated_at: now,
      custom_fields: JSON.stringify({
        capacity_mwp: '3',
        roof_area_sqm: '25000',
        land_type: '建设用地',
        grid_voltage: '380V',
        target_substation: '临安10kV',
        access_approval_status: '未办理',
        filing_status: '备案中',
        planned_grid_date: '2025-03-01',
        construction_progress: '未开工',
        operation_status: '在建',
        annual_irradiance: '1400',
        sunshine_hours: '1520',
        solar_grade: 'A',
        unit_cost: '4.0',
        payback_years: '6.5',
        irr_pct: '15.0',
        env_sensitivity: '不敏感',
        geohazard_risk: '低',
      }),
    },
    {
      id: uuid(),
      project_code: 'PV-DT-2024-002',
      project_name: '滨江屋顶分布式光伏项目',
      project_type: typeMap['PV_DISTRIBUTED'],
      pv_type: '分布式',
      capacity_kw: 1500,
      budget: '600',
      status: 'feasibility',
      start_date: '2024-09-01',
      expected_completion_date: '2025-06-01',
      actual_completion_date: null,
      created_by: adminId,
      created_at: now,
      updated_at: now,
      custom_fields: JSON.stringify({
        capacity_mwp: '1.5',
        roof_area_sqm: '12000',
        land_type: '建设用地',
        grid_voltage: '380V',
        target_substation: '滨江10kV',
        access_approval_status: '未办理',
        filing_status: '已备案',
        planned_grid_date: '2025-06-01',
        construction_progress: '未开工',
        operation_status: '在建',
        annual_irradiance: '1420',
        sunshine_hours: '1550',
        solar_grade: 'A',
        unit_cost: '4.0',
        payback_years: '6.0',
        irr_pct: '16.5',
        env_sensitivity: '不敏感',
        geohazard_risk: '低',
      }),
    },
    {
      id: uuid(),
      project_code: 'PV-GC-2025-002',
      project_name: '富阳渔山二期扩产项目',
      project_type: typeMap['PV_GRID_CONNECTION'],
      pv_type: '集中式',
      capacity_kw: 20000,
      budget: '8000',
      status: 'initiated',
      start_date: '2025-03-01',
      expected_completion_date: '2026-03-01',
      actual_completion_date: null,
      created_by: adminId,
      created_at: now,
      updated_at: now,
      custom_fields: JSON.stringify({
        capacity_mwp: '20',
        land_type: '未利用地',
        grid_voltage: '10kV',
        target_substation: '富阳10kV',
        access_approval_status: '未办理',
        filing_status: '未备案',
        planned_grid_date: '2026-03-01',
        construction_progress: '未开工',
        operation_status: '在建',
        annual_irradiance: '1360',
        sunshine_hours: '1420',
        solar_grade: 'B',
        unit_cost: '4.2',
        payback_years: '9.5',
        irr_pct: '8.5',
        env_sensitivity: '敏感',
        geohazard_risk: '中',
        short_circuit_capacity_mva: '100',
        transmission_distance_km: '4.0',
        corridor_available: '受限',
      }),
    },
  ]

  await knex('projects').insert(projects)
  console.log(`  ✓ ${projects.length} 个规划项目已创建`)
}
