import type { Knex } from 'knex'
import { v4 as uuid } from 'uuid'

export async function seed(knex: Knex): Promise<void> {
  await knex('assessment_model_fields').del()

  const now = new Date().toISOString()

  const fields = [
    // ==================== 资源维度 ====================
    {
      id: uuid(),
      field_code: 'annual_irradiance',
      field_name: '年均辐照度',
      field_desc: '项目所在地年均太阳辐照度，反映太阳能资源丰裕程度',
      field_type: 'numeric',
      dimension: 'resource',
      base_value: 1600,
      score_rule: 'direct_ratio',
      max_score: 100,
      fail_score: 0,
      sort_order: 1,
      is_active: 1,
      created_at: now,
    },
    {
      id: uuid(),
      field_code: 'sunshine_hours',
      field_name: '年日照小时数',
      field_desc: '项目所在地年均日照小时数',
      field_type: 'numeric',
      dimension: 'resource',
      base_value: 1400,
      score_rule: 'direct_ratio',
      max_score: 100,
      fail_score: 0,
      sort_order: 2,
      is_active: 1,
      created_at: now,
    },
    {
      id: uuid(),
      field_code: 'solar_grade',
      field_name: '太阳能资源等级',
      field_desc: '国家太阳能资源区划等级，A级最优',
      field_type: 'text',
      dimension: 'resource',
      base_value: 3,
      score_rule: 'map_direct',
      text_map: JSON.stringify({ A: 4, B: 3, C: 2 }),
      max_score: 100,
      fail_score: 0,
      sort_order: 3,
      is_active: 1,
      created_at: now,
    },
    {
      id: uuid(),
      field_code: 'capacity_mwp',
      field_name: '装机容量',
      field_desc: '规划装机容量（MWp），反映项目规模',
      field_type: 'numeric',
      dimension: 'resource',
      base_value: 50,
      score_rule: 'direct_ratio',
      max_score: 100,
      fail_score: 0,
      sort_order: 4,
      is_active: 1,
      created_at: now,
    },

    // ==================== 电网维度 ====================
    {
      id: uuid(),
      field_code: 'grid_voltage',
      field_name: '并网电压等级',
      field_desc: '拟接入电网的电压等级',
      field_type: 'text',
      dimension: 'grid',
      base_value: 110,
      score_rule: 'map_direct',
      text_map: JSON.stringify({ '220V': 0.22, '380V': 0.38, '10kV': 10, '35kV': 35, '110kV': 110, '220kV': 220 }),
      max_score: 100,
      fail_score: 0,
      sort_order: 1,
      is_active: 1,
      created_at: now,
    },
    {
      id: uuid(),
      field_code: 'short_circuit_capacity_mva',
      field_name: '短路容量',
      field_desc: '接入点母线短路容量（MVA），反映电网承载能力',
      field_type: 'numeric',
      dimension: 'grid',
      base_value: 200,
      score_rule: 'direct_ratio',
      max_score: 100,
      fail_score: 0,
      sort_order: 2,
      is_active: 1,
      created_at: now,
    },
    {
      id: uuid(),
      field_code: 'transmission_distance_km',
      field_name: '接入距离',
      field_desc: '光伏电站至并网点的输电线路距离（km）',
      field_type: 'numeric',
      dimension: 'grid',
      base_value: 5,
      score_rule: 'inverse_ratio',
      max_score: 100,
      fail_score: 0,
      sort_order: 3,
      is_active: 1,
      created_at: now,
    },
    {
      id: uuid(),
      field_code: 'corridor_available',
      field_name: '线路走廊可用性',
      field_desc: '输电线路走廊是否可用',
      field_type: 'text',
      dimension: 'grid',
      score_rule: 'match_full',
      match_value: '可用',
      max_score: 100,
      fail_score: 0,
      sort_order: 4,
      is_active: 1,
      created_at: now,
    },

    // ==================== 投资维度 ====================
    {
      id: uuid(),
      field_code: 'unit_cost',
      field_name: '单位造价',
      field_desc: '项目单位千瓦造价（元/W）',
      field_type: 'numeric',
      dimension: 'investment',
      base_value: 3.5,
      score_rule: 'inverse_ratio',
      max_score: 100,
      fail_score: 0,
      sort_order: 1,
      is_active: 1,
      created_at: now,
    },
    {
      id: uuid(),
      field_code: 'payback_years',
      field_name: '投资回收期',
      field_desc: '项目投资静态回收期（年）',
      field_type: 'numeric',
      dimension: 'investment',
      base_value: 6,
      score_rule: 'inverse_ratio',
      max_score: 100,
      fail_score: 0,
      sort_order: 2,
      is_active: 1,
      created_at: now,
    },
    {
      id: uuid(),
      field_code: 'irr_pct',
      field_name: '内部收益率',
      field_desc: '项目全投资内部收益率（%）',
      field_type: 'numeric',
      dimension: 'investment',
      base_value: 10,
      score_rule: 'direct_ratio',
      max_score: 100,
      fail_score: 0,
      sort_order: 3,
      is_active: 1,
      created_at: now,
    },

    // ==================== 环境维度 ====================
    {
      id: uuid(),
      field_code: 'land_type',
      field_name: '土地性质',
      field_desc: '项目用地类型，未利用地最优',
      field_type: 'text',
      dimension: 'environment',
      score_rule: 'map_fixed',
      text_map: JSON.stringify({ '未利用地': 80, '建设用地': 60, '草地': 40, '农用地': 20, '林地': 20 }),
      max_score: 100,
      fail_score: 0,
      sort_order: 1,
      is_active: 1,
      created_at: now,
    },
    {
      id: uuid(),
      field_code: 'env_sensitivity',
      field_name: '环保敏感性',
      field_desc: '项目区域环保敏感程度',
      field_type: 'text',
      dimension: 'environment',
      score_rule: 'map_fixed',
      text_map: JSON.stringify({ '不敏感': 90, '一般': 50, '敏感': 20 }),
      max_score: 100,
      fail_score: 0,
      sort_order: 2,
      is_active: 1,
      created_at: now,
    },
    {
      id: uuid(),
      field_code: 'geohazard_risk',
      field_name: '地质灾害风险',
      field_desc: '项目区域地质灾害风险等级',
      field_type: 'text',
      dimension: 'environment',
      score_rule: 'map_fixed',
      text_map: JSON.stringify({ '低': 90, '中': 50, '高': 20 }),
      max_score: 100,
      fail_score: 0,
      sort_order: 3,
      is_active: 1,
      created_at: now,
    },
  ]

  await knex('assessment_model_fields').insert(fields)
}
